# Welcome to Jekyll!


title: Econ100A Intermediate Microeconomics


description: >- # this means to ignore newlines until "baseurl:"
  UCSC Economics Department 2020

baseurl: "/IntermMicroecon_UCSC" # the subpath of your site, e.g. /blog

#site_url: https://klmv.github.io/IntermMircoecon_UCSC/

url: "http://klmv.github.io"  # the base hostname & protocol for your site, e.g. http://example.com


# Build settings

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
